### ISSUE TITLE
Inventory geht nicht

### ISSUE THREAD

**Issue by Lukas006** [LPDMinecraft/Challenges-Plugin#1]
Wenn ich das Inventory von einer Challenge versuche zu öffen, dann funktioniert es nicht.

**Comment by LPDMinecraft** [comment]
Ich weiß. Ich werde nächstes Wochenende dran arbeiten

**Comment by Lukas006** [comment]
okey

**Comment by Lukas006** [comment]
Wenn ich das Inventory von einer Challenge versuche zu öffen, dann funktioniert es nicht.

**Comment by LPDMinecraft** [comment]
Ich weiß. Ich werde nächstes Wochenende dran arbeiten

**Comment by LPDMinecraft** [comment]
Habe es jetzt in der neuesten Version gefixt.
